#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S2,     rightT,         sensorTouch)
#pragma config(Sensor, S3,     leftT,          sensorTouch)
#pragma config(Motor,  motorA,          Hand,          tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          Arm,           tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     Right,         tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Left,          tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S4_C1_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S4_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "Header.h"
// e-stop allows you to hit the touch sensors as immediatelykill the robot.

task e_stop()
{
	while(true)
	{
		if(SensorValue(rightT) == 1)
		{
			stopAllTasks(); // this ends the program
		}
		else if (SensorValue(leftT) == 1)
		{
			stopAllTasks();
		}
		wait1Msec(10);  // this prevents the current task from hogging the CPU
	}
}


task main()
{

	waitForStart();
	startTask(e_stop);


	while(true)
	{
		getJoystickSettings(joystick);
		if (joystick.joy1_y1 > 10)
		{
			motor[Left] = power;
		}
		else if (joystick.joy1_y1 < -10)
		{
			motor[Left] = -power;
		}
		else
		{
			motor[Left] = 0;
		}
		getJoystickSettings(joystick);
		if (joystick.joy1_y2 > 10)
		{
			motor[Right] = power;
		}
		else if (joystick.joy1_y2 < -10)
		{
			motor[Right] = -power;
		}
		else
		{
			motor[Right] = 0;
		}
		//-------------------------------------------------------------- Rear Servo
		//if (joy1Btn(5)) //up

		//{
		//	sev = sev - 5;
		//	if (sev < 80)
		//	{
		//		sev = 80;
		//	}
		//	servo[servo1] = sev;
		//	wait1Msec(100);
		//}

		//if (joy1Btn(7)) // down
		//{
		//	sev = sev + 5;
		//	if (sev > 200)
		//	{
		//		sev = 200;
		//	}
		//	servo[servo1] = sev;
		//	wait1Msec(100);
		//}


		//getJoystickSettings(joystick);
		//if (joy1Btn(5))
		//{
		//	servo[servo1] = 0;
		//	wait1Msec(100);
		//}
		//getJoystickSettings(joystick);
		//if (joy1Btn(7))
		//{
		//	servo[servo1] = 80;
		//	wait1Msec(100);
		//}
		////--------------------------

		//getJoystickSettings(joystick);
		////servoChangeRate[servo1] = 10;
		//if (joy1Btn(8))
		//{
		//	servo[servo1] = ServoValue[servo1] + 5;
		//	wait1Msec(1200);
		//}
		//getJoystickSettings(joystick);
		//if (joy1Btn(6))
		//{
		//	servo[servo1] = ServoValue[servo1] - 5;
		//	wait1Msec(1200);
		//}

		//-------------------------------------------------------------- Variable Button Speeds
		getJoystickSettings(joystick);
		if (joy1Btn(1))
		{
			//playSound(soundBeepBeep);
			//wait1Msec(500);
			power = pwr1;
		}
		if (joy1Btn(2))
		{
			//playSound(soundBeepBeep);
			//wait1Msec(500);
			power = pwr2;
		}
		if (joy1Btn(3))
		{
			//playSound(soundBeepBeep);
			//wait1Msec(500);
			power = pwr3;
		}
		if (joy1Btn(4))
		{
			//playSound(soundBeepBeep);
			//wait1Msec(500);
			power = pwr4;
		}
		//-------------------------------------------------------------------- NXT Motors
		//2-6 motor B, 0-4 motor A
		if (joystick.joy1_TopHat == 6)//right					//6 = right, 2 = left
		{
			motor[motorB] = 60;
		}
		else if (joystick.joy1_TopHat == 2)//left
		{
			motor[motorB] = -60;
		}
		else
		{
			motor[motorB] = 0;
		}
		//-------------------------
		if (joystick.joy1_TopHat == 0)//open
		{
			motor[motorA] = 75;
		}
		else if (joystick.joy1_TopHat == 4)//close
		{
			motor[motorA] = -50;
		}
		else
		{
			motor[motorA] = 0;
		}
	}
}












//-------------------------------------------------------------
/*
while(true)
{
getJoystickSettings(joystick);
if (joystick.joy1_y1 > 10)
{
motor[Left] = 25;
}
else if (joystick.joy1_y1 < -10)
{
motor[Left] = -25;
}
else
{
motor[Left] = 0;
}
getJoystickSettings(joystick);
if (joystick.joy1_y2 > 10)
{
motor[Right] = 25;
}
else if (joystick.joy1_y2 < -10)
{
motor[Right] = -25;
}
else
{
motor[Right] = 0;
}
}
*/
